#!/usr/bin/env python3
"""Visualize temporal SWC context features on EVUAV or EV-Flying.

The main paper figure produced by this tool contains two aligned rows:

1. raw EVUAV events with point-level target ground truth highlighted;
2. GT-free relative saliency derived only from the continuously updated SWC
   context tensor.

The first row accumulates the target trajectory from left to right, using
different colors for past and newly appended target events.  The model still
runs through the complete sample.  Only the requested windows are retained for
plotting, so their SWC states include all preceding windows.  Ground truth is
never used to normalize, aggregate, enhance, or color-scale the context map.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import os
import random
import sys
from pathlib import Path
from types import SimpleNamespace
from typing import Any, Dict, List, Mapping, Sequence

# Must be set before the first CUDA context is created.  This keeps the two
# verification forwards reproducible without emitting CuBLAS warnings.
os.environ.setdefault("CUBLAS_WORKSPACE_CONFIG", ":16:8")

import numpy as np
import torch
import yaml


REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

DEFAULT_RUN_DIR = (
    REPO_ROOT
    / "save_model/grid_mamba/ablation_sparse_conv/SC12_GS_G4_FINE_LOW_MID"
)
DEFAULT_CONFIG = DEFAULT_RUN_DIR / "train_config.yaml"
DEFAULT_CHECKPOINT = DEFAULT_RUN_DIR / "best_loss_seed37.pt"
DEFAULT_SAMPLE = REPO_ROOT / "dataset/EV-UAV-dataset/test/test_020.npz"
DEFAULT_OUTPUT_DIR = (
    REPO_ROOT / "analysis_outputs/evuav_swc_temporal/test_020_w11_15"
)
OUTPUT_FILES = (
    "swc_temporal_main.png",
    "swc_temporal_main.pdf",
    "swc_temporal_diagnostic.png",
    "swc_temporal_maps.npz",
    "window_metrics.csv",
    "summary.json",
)
STALE_OUTPUT_FILES = (
    "swc_temporal_cumulative_trajectory.png",
    "swc_temporal_cumulative_trajectory.pdf",
)
CONTEXT_SALIENCY_COLORMAP = "RdBu_r"
RAW_CONTEXT_COLORMAP = "cividis"
RAW_CONTEXT_COLOR_LOW_QUANTILE = 0.50
RAW_CONTEXT_COLOR_HIGH_QUANTILE = 0.995
CONTEXT_SALIENCY_COLOR_QUANTILE = 0.995
ROBUST_MAD_NORMALIZATION = 1.4826
ROBUST_SCALE_EPSILON = 1e-6
CONTEXT_SMOOTH_KERNEL_SIZE = 3
CONTEXT_LOCAL_MEDIAN_KERNEL_SIZE = 7


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Create aligned event-dataset ground-truth and SWC context-feature "
            "heatmaps for consecutive model windows."
        )
    )
    parser.add_argument("--config", default=str(DEFAULT_CONFIG))
    parser.add_argument("--checkpoint", default=str(DEFAULT_CHECKPOINT))
    parser.add_argument("--sample", default=str(DEFAULT_SAMPLE))
    parser.add_argument("--start-window", type=int, default=11)
    parser.add_argument("--num-windows", type=int, default=5)
    parser.add_argument("--threshold", type=float, default=0.41)
    parser.add_argument("--device", default="cuda:0")
    parser.add_argument("--output-dir", default=str(DEFAULT_OUTPUT_DIR))
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Replace files generated by an earlier invocation.",
    )
    return parser.parse_args()


def resolve_path(value: str | Path) -> Path:
    path = Path(value).expanduser()
    if not path.is_absolute():
        path = REPO_ROOT / path
    return path.resolve()


def relative_or_absolute(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(REPO_ROOT))
    except ValueError:
        return str(path.resolve())


def read_config(path: Path) -> tuple[SimpleNamespace, Mapping[str, Any]]:
    with path.open("r", encoding="utf-8") as handle:
        raw = yaml.safe_load(handle)
    if not isinstance(raw, Mapping):
        raise ValueError(f"Config must be a mapping: {path}")

    flattened: Dict[str, Any] = {"config": str(path)}
    for section_name, section in raw.items():
        if not isinstance(section, Mapping):
            raise ValueError(
                f"Config section {section_name!r} must be a mapping: {path}"
            )
        for key, value in section.items():
            flattened[str(key)] = value
    return SimpleNamespace(**flattened), raw


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def json_value(value: Any) -> Any:
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, np.generic):
        return value.item()
    if isinstance(value, np.ndarray):
        return value.tolist()
    if torch.is_tensor(value):
        return value.detach().cpu().tolist()
    raise TypeError(f"Cannot serialize {type(value).__name__}")


def prepare_output_dir(output_dir: Path, overwrite: bool) -> None:
    managed_files = OUTPUT_FILES + STALE_OUTPUT_FILES
    existing = [
        output_dir / name
        for name in managed_files
        if (output_dir / name).exists()
    ]
    if existing and not overwrite:
        formatted = "\n  ".join(str(path) for path in existing)
        raise FileExistsError(
            "Output files already exist. Pass --overwrite to replace them:\n  "
            + formatted
        )
    output_dir.mkdir(parents=True, exist_ok=True)
    if overwrite:
        for path in existing:
            path.unlink()


def setup_runtime(seed: int = 37) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    torch.use_deterministic_algorithms(True, warn_only=True)


def validate_args(args: argparse.Namespace) -> None:
    if args.start_window < 0:
        raise ValueError("--start-window must be non-negative")
    if args.num_windows <= 0:
        raise ValueError("--num-windows must be positive")
    if not 0.0 <= args.threshold <= 1.0:
        raise ValueError("--threshold must be in [0, 1]")
    if not str(args.device).startswith("cuda"):
        raise ValueError("This tool requires a CUDA device; CPU fallback is unsupported")
    if not torch.cuda.is_available():
        raise RuntimeError("CUDA is required but torch.cuda.is_available() is False")


def load_sample(path: Path) -> tuple[np.ndarray, np.ndarray]:
    with np.load(path) as payload:
        required = {"ev_loc", "evs_norm"}
        missing = required.difference(payload.files)
        if missing:
            raise KeyError(f"Missing arrays in {path}: {sorted(missing)}")
        points = np.asarray(payload["ev_loc"][:, :3], dtype=np.float32)
        labels = np.asarray(payload["evs_norm"][:, 4], dtype=np.float32)

    if points.ndim != 2 or points.shape[1] != 3:
        raise ValueError(f"Expected ev_loc[:, :3] with shape [N, 3], got {points.shape}")
    if labels.ndim != 1 or labels.shape[0] != points.shape[0]:
        raise ValueError(
            f"Expected one label per point, got points={points.shape}, labels={labels.shape}"
        )
    if points.shape[0] == 0:
        raise ValueError(f"Sample contains no events: {path}")
    if not np.isfinite(points).all() or not np.isfinite(labels).all():
        raise ValueError(f"Sample contains non-finite values: {path}")
    return points, labels


def validate_model_config(model: torch.nn.Module, cfg: SimpleNamespace) -> None:
    if not bool(getattr(model, "use_spatial_window_context", False)):
        raise ValueError("The selected config has use_spatial_window_context=False")
    if model.spatial_window_context is None:
        raise ValueError("The selected model has no SpatialWindowContext module")

    window_size = float(getattr(cfg, "window_size"))
    stride = float(getattr(cfg, "spatial_context_stride"))
    if window_size <= 0.0:
        raise ValueError(f"window_size must be positive, got {window_size}")
    if stride <= 0.0:
        raise ValueError(f"spatial_context_stride must be positive, got {stride}")

    sensor_size = tuple(int(value) for value in getattr(cfg, "sensor_size"))
    if len(sensor_size) != 2 or min(sensor_size) <= 0:
        raise ValueError(f"sensor_size must contain positive [height, width], got {sensor_size}")

    swc = model.spatial_window_context
    expected_shape = (
        int(math.ceil(sensor_size[0] / stride)),
        int(math.ceil(sensor_size[1] / stride)),
    )
    actual_shape = (swc.spatial_token_h, swc.spatial_token_w)
    if actual_shape != expected_shape:
        raise ValueError(
            f"Expected a {expected_shape[0]}x{expected_shape[1]} SWC map, got "
            f"{actual_shape[0]}x{actual_shape[1]}"
        )


def make_window_layout(
    points: torch.Tensor,
    labels: torch.Tensor,
    window_size: float,
) -> Dict[str, torch.Tensor]:
    sort_idx = torch.argsort(points[:, 2])
    points_sorted = points[sort_idx]
    labels_sorted = labels[sort_idx]
    window_ids = torch.div(
        points_sorted[:, 2] - points_sorted[0, 2],
        window_size,
        rounding_mode="floor",
    ).long()
    _, counts = torch.unique_consecutive(window_ids, return_counts=True)
    offsets = torch.zeros(counts.numel() + 1, dtype=torch.long, device=points.device)
    torch.cumsum(counts, dim=0, out=offsets[1:])
    return {
        "sort_idx": sort_idx,
        "points": points_sorted,
        "labels": labels_sorted,
        "window_ids": window_ids,
        "counts": counts,
        "offsets": offsets,
    }


def capture_swc_windows(
    model: torch.nn.Module,
    points: torch.Tensor,
    start_window: int,
    num_windows: int,
) -> tuple[torch.Tensor, List[Dict[str, torch.Tensor]]]:
    swc = model.spatial_window_context
    original_step = swc.step
    stop_window = start_window + num_windows
    captures: List[Dict[str, torch.Tensor]] = []
    window_counter = 0

    def traced_step(
        window_points: torch.Tensor,
        fused_feat: torch.Tensor,
        state=None,
        cell_idx: torch.Tensor | None = None,
    ):
        nonlocal window_counter
        current_window = window_counter
        window_counter += 1

        if cell_idx is None:
            cell_idx = swc._get_spatial_cell_indices(window_points)

        should_capture = start_window <= current_window < stop_window
        pre_prob = None
        if should_capture:
            pre_prob = torch.sigmoid(model._classify_features(fused_feat).float())

        enhanced_feat, new_state = original_step(
            window_points,
            fused_feat,
            state,
            cell_idx=cell_idx,
        )

        if should_capture:
            post_prob = torch.sigmoid(model._classify_features(enhanced_feat).float())
            captures.append(
                {
                    "window_index": torch.tensor(current_window, dtype=torch.int64),
                    "points": window_points.detach().float().cpu(),
                    "cell_idx": cell_idx.detach().long().cpu(),
                    "pre_prob": pre_prob.detach().float().cpu(),
                    "post_prob": post_prob.detach().float().cpu(),
                    "raw_token_map": new_state["prev_raw_token_map"]
                    .detach()
                    .float()
                    .cpu(),
                    "effective_token_map": new_state["prev_token_map"]
                    .detach()
                    .float()
                    .cpu(),
                    "context_map": new_state["prev_context_map"]
                    .detach()
                    .float()
                    .cpu(),
                }
            )
        return enhanced_feat, new_state

    swc.step = traced_step
    try:
        traced_logits, _ = model(points)
    finally:
        swc.step = original_step

    if traced_logits is None:
        raise RuntimeError("Model returned no logits")
    if len(captures) != num_windows:
        raise RuntimeError(
            f"Expected {num_windows} captured windows, got {len(captures)}; "
            f"the sample contains {window_counter} model windows"
        )
    return traced_logits, captures


def auc_binary(labels: np.ndarray, scores: np.ndarray) -> float:
    labels = np.asarray(labels, dtype=np.int64)
    scores = np.asarray(scores, dtype=np.float64)
    positive = labels == 1
    negative = labels == 0
    num_positive = int(positive.sum())
    num_negative = int(negative.sum())
    if num_positive == 0 or num_negative == 0:
        return float("nan")

    order = np.argsort(scores, kind="mergesort")
    sorted_scores = scores[order]
    ranks = np.empty(scores.size, dtype=np.float64)
    start = 0
    while start < scores.size:
        end = start + 1
        while end < scores.size and sorted_scores[end] == sorted_scores[start]:
            end += 1
        ranks[order[start:end]] = 0.5 * (start + 1 + end)
        start = end
    rank_sum = float(ranks[positive].sum())
    return (
        rank_sum - num_positive * (num_positive + 1) / 2.0
    ) / (num_positive * num_negative)


def safe_ratio(numerator: float, denominator: float) -> float:
    return float(numerator / denominator) if denominator > 0 else 0.0


def aggregate_cell_values(
    capture: Mapping[str, torch.Tensor],
    labels: torch.Tensor,
    token_h: int,
    token_w: int,
    threshold: float,
) -> tuple[Dict[str, np.ndarray], Dict[str, Any], Dict[str, np.ndarray]]:
    num_cells = token_h * token_w
    cell_idx = capture["cell_idx"].numpy().astype(np.int64, copy=False)
    labels_np = labels.detach().float().cpu().numpy()
    pre_prob = capture["pre_prob"].numpy()
    post_prob = capture["post_prob"].numpy()
    delta_prob = post_prob - pre_prob

    if labels_np.shape[0] != cell_idx.shape[0]:
        raise ValueError(
            f"Label/capture length mismatch: labels={labels_np.shape[0]}, "
            f"captured={cell_idx.shape[0]}"
        )

    event_count = np.bincount(cell_idx, minlength=num_cells).astype(np.int64)
    target_count = np.bincount(
        cell_idx,
        weights=labels_np,
        minlength=num_cells,
    ).astype(np.float64)
    post_sum = np.bincount(cell_idx, weights=post_prob, minlength=num_cells)
    delta_sum = np.bincount(cell_idx, weights=delta_prob, minlength=num_cells)
    occupied = event_count > 0

    gt_ratio = np.divide(
        target_count,
        event_count,
        out=np.zeros(num_cells, dtype=np.float64),
        where=occupied,
    )
    post_map = np.divide(
        post_sum,
        event_count,
        out=np.zeros(num_cells, dtype=np.float64),
        where=occupied,
    )
    delta_map = np.divide(
        delta_sum,
        event_count,
        out=np.zeros(num_cells, dtype=np.float64),
        where=occupied,
    )

    context_map = capture["context_map"].numpy()
    context_l2 = np.linalg.norm(context_map, axis=-1).reshape(-1)
    raw_token_map = capture["raw_token_map"].numpy()
    raw_token_l2 = np.linalg.norm(raw_token_map, axis=-1).reshape(-1)

    target_cells = (target_count > 0) & occupied
    background_cells = (~target_cells) & occupied
    predicted = post_prob >= threshold
    truth = labels_np >= 0.5
    tp = int(np.logical_and(predicted, truth).sum())
    fp = int(np.logical_and(predicted, ~truth).sum())
    fn = int(np.logical_and(~predicted, truth).sum())
    tn = int(np.logical_and(~predicted, ~truth).sum())

    points_np = capture["points"].numpy()
    target_points = points_np[truth, :2]
    if target_points.size == 0:
        centroid = np.array([np.nan, np.nan], dtype=np.float64)
    else:
        centroid = np.median(target_points, axis=0).astype(np.float64)

    occupied_target_labels = target_cells[occupied].astype(np.int64)
    metrics = {
        "num_events": int(labels_np.size),
        "num_target_events": int(truth.sum()),
        "num_occupied_cells": int(occupied.sum()),
        "num_target_cells": int(target_cells.sum()),
        "centroid_x": float(centroid[0]),
        "centroid_y": float(centroid[1]),
        "tp": tp,
        "fp": fp,
        "fn": fn,
        "tn": tn,
        "iou": safe_ratio(tp, tp + fp + fn),
        "pd": safe_ratio(tp, tp + fn),
        "fa": safe_ratio(fp, fp + tn),
        "precision": safe_ratio(tp, tp + fp),
        "mean_delta_target_cells": float(delta_map[target_cells].mean()),
        "mean_delta_background_cells": float(delta_map[background_cells].mean()),
        "mean_context_target_cells": float(context_l2[target_cells].mean()),
        "mean_context_background_cells": float(context_l2[background_cells].mean()),
        "auc_delta_prob": auc_binary(
            occupied_target_labels,
            delta_map[occupied],
        ),
        "auc_context_l2": auc_binary(
            occupied_target_labels,
            context_l2[occupied],
        ),
        "auc_post_prob": auc_binary(
            occupied_target_labels,
            post_map[occupied],
        ),
        "auc_raw_token_l2": auc_binary(
            occupied_target_labels,
            raw_token_l2[occupied],
        ),
    }
    maps = {
        "gt_ratio": gt_ratio.reshape(token_h, token_w).astype(np.float32),
        "delta_prob": delta_map.reshape(token_h, token_w).astype(np.float32),
        "post_prob": post_map.reshape(token_h, token_w).astype(np.float32),
        "context_l2": context_l2.reshape(token_h, token_w).astype(np.float32),
        "raw_token_l2": raw_token_l2.reshape(token_h, token_w).astype(np.float32),
        "occupied_mask": occupied.reshape(token_h, token_w),
        "event_count": event_count.reshape(token_h, token_w),
        "target_count": target_count.reshape(token_h, token_w).astype(np.float32),
    }
    point_values = {
        "points": points_np.astype(np.float32, copy=False),
        "labels": labels_np.astype(np.float32, copy=False),
        "cell_idx": cell_idx,
        "pre_prob": pre_prob.astype(np.float32, copy=False),
        "post_prob": post_prob.astype(np.float32, copy=False),
        "delta_prob": delta_prob.astype(np.float32, copy=False),
    }
    return maps, metrics, point_values


def robust_symmetric_limit(values: np.ndarray, quantile: float = 0.99) -> float:
    finite = np.abs(values[np.isfinite(values)])
    if finite.size == 0:
        return 1.0
    limit = float(np.quantile(finite, quantile))
    if limit <= 0.0:
        limit = float(finite.max(initial=0.0))
    return max(limit, 1e-6)


def shared_percentile_limits(
    values: np.ndarray,
    low: float = 0.02,
    high: float = 0.98,
) -> tuple[float, float]:
    finite = values[np.isfinite(values)]
    if finite.size == 0:
        return 0.0, 1.0
    vmin = float(np.quantile(finite, low))
    vmax = float(np.quantile(finite, high))
    if math.isclose(vmin, vmax):
        vmax = vmin + 1e-6
    return vmin, vmax


def spatial_binomial_smooth(values: np.ndarray) -> np.ndarray:
    """Apply a reflection-padded 3x3 binomial filter independently per window."""
    if values.ndim != 3:
        raise ValueError(f"Expected [T, H, W] values, got {values.shape}")
    kernel = np.asarray(
        [[1.0, 2.0, 1.0], [2.0, 4.0, 2.0], [1.0, 2.0, 1.0]],
        dtype=np.float64,
    )
    kernel /= kernel.sum()
    padded = np.pad(values, ((0, 0), (1, 1), (1, 1)), mode="reflect")
    windows = np.lib.stride_tricks.sliding_window_view(
        padded,
        (CONTEXT_SMOOTH_KERNEL_SIZE, CONTEXT_SMOOTH_KERNEL_SIZE),
        axis=(1, 2),
    )
    return np.einsum("thwij,ij->thw", windows, kernel, optimize=True)


def spatial_median_filter(values: np.ndarray, kernel_size: int) -> np.ndarray:
    """Apply a reflection-padded spatial median independently per window."""
    if values.ndim != 3:
        raise ValueError(f"Expected [T, H, W] values, got {values.shape}")
    if kernel_size <= 0 or kernel_size % 2 == 0:
        raise ValueError(f"Median kernel must be a positive odd integer, got {kernel_size}")
    radius = kernel_size // 2
    padded = np.pad(
        values,
        ((0, 0), (radius, radius), (radius, radius)),
        mode="reflect",
    )
    windows = np.lib.stride_tricks.sliding_window_view(
        padded,
        (kernel_size, kernel_size),
        axis=(1, 2),
    )
    return np.median(windows, axis=(-2, -1))


def compute_gt_free_context_saliency(
    context_features: np.ndarray,
) -> Dict[str, np.ndarray]:
    """Derive context saliency using only the selected SWC context tensors.

    Channels are robustly standardized over all selected windows and spatial
    cells.  Their root-mean-square energy is lightly smoothed, then a 7x7 local
    median is subtracted to expose responses that stand above their local
    context background.  No labels, occupancy mask, point probabilities, or
    target locations enter this computation.
    """
    context = np.asarray(context_features, dtype=np.float64)
    if context.ndim != 4:
        raise ValueError(
            f"Expected context features with shape [T, H, W, C], got {context.shape}"
        )
    if not np.isfinite(context).all():
        raise ValueError("Context features contain non-finite values")

    reduce_axes = (0, 1, 2)
    channel_center = np.median(context, axis=reduce_axes)
    absolute_deviation = np.abs(context - channel_center[None, None, None, :])
    mad_scale = ROBUST_MAD_NORMALIZATION * np.median(
        absolute_deviation,
        axis=reduce_axes,
    )

    # The IQR and standard-deviation fallbacks make the tool safe for sparse
    # channels whose median absolute deviation is exactly zero.  Constant
    # channels are marked inactive and contribute zero standardized energy.
    quartiles = np.quantile(context, (0.25, 0.75), axis=reduce_axes)
    iqr_scale = (quartiles[1] - quartiles[0]) / 1.349
    std_scale = np.std(context, axis=reduce_axes)
    channel_scale = mad_scale.copy()
    scale_source = np.zeros(channel_scale.shape, dtype=np.uint8)

    use_iqr = (channel_scale < ROBUST_SCALE_EPSILON) & (
        iqr_scale >= ROBUST_SCALE_EPSILON
    )
    channel_scale[use_iqr] = iqr_scale[use_iqr]
    scale_source[use_iqr] = 1

    use_std = (channel_scale < ROBUST_SCALE_EPSILON) & (
        std_scale >= ROBUST_SCALE_EPSILON
    )
    channel_scale[use_std] = std_scale[use_std]
    scale_source[use_std] = 2

    inactive = channel_scale < ROBUST_SCALE_EPSILON
    channel_scale[inactive] = 1.0
    scale_source[inactive] = 3

    standardized = (
        context - channel_center[None, None, None, :]
    ) / channel_scale[None, None, None, :]
    if inactive.any():
        standardized[..., inactive] = 0.0

    standardized_energy = np.sqrt(np.mean(np.square(standardized), axis=-1))
    smoothed_energy = spatial_binomial_smooth(standardized_energy)
    local_baseline = spatial_median_filter(
        smoothed_energy,
        CONTEXT_LOCAL_MEDIAN_KERNEL_SIZE,
    )
    saliency = smoothed_energy - local_baseline

    outputs = {
        "context_standardized_energy": standardized_energy.astype(np.float32),
        "context_smoothed_energy": smoothed_energy.astype(np.float32),
        "context_local_median": local_baseline.astype(np.float32),
        "context_saliency": saliency.astype(np.float32),
        "context_channel_center": channel_center.astype(np.float32),
        "context_channel_scale": channel_scale.astype(np.float32),
        "context_channel_scale_source": scale_source,
    }
    for key, value in outputs.items():
        if not np.isfinite(value).all():
            raise AssertionError(f"Derived array {key} contains non-finite values")
    return outputs


def configure_matplotlib() -> None:
    os.environ.setdefault("MPLCONFIGDIR", "/tmp/grid_mamba_matplotlib")
    import matplotlib

    matplotlib.use("Agg")
    matplotlib.rcParams.update(
        {
            "font.family": "DejaVu Serif",
            "font.size": 9,
            "axes.titlesize": 10,
            "axes.labelsize": 9,
            "xtick.labelsize": 8,
            "ytick.labelsize": 8,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )


def plot_main_figure(
    point_values: Sequence[Mapping[str, np.ndarray]],
    target_centroids: np.ndarray,
    context_saliency: np.ndarray,
    window_bounds: np.ndarray,
    sensor_height: int,
    sensor_width: int,
    saliency_limit: float,
    output_dir: Path,
    cumulative_trajectory: bool = False,
) -> None:
    import matplotlib.pyplot as plt
    from matplotlib.colors import TwoSlopeNorm
    from matplotlib.lines import Line2D

    num_windows = context_saliency.shape[0]
    if len(point_values) != num_windows:
        raise ValueError(
            f"Expected point data for {num_windows} windows, got {len(point_values)}"
        )
    fig, axes = plt.subplots(
        2,
        num_windows,
        figsize=(2.55 * num_windows + 1.2, 5.1),
        sharex=True,
        sharey=True,
        constrained_layout=True,
    )
    axes = np.asarray(axes).reshape(2, num_windows)
    extent = (0, sensor_width, sensor_height, 0)
    saliency_norm = TwoSlopeNorm(
        vmin=-saliency_limit,
        vcenter=0.0,
        vmax=saliency_limit,
    )
    background_color = "#777777"
    target_color = "#C62828"
    past_target_color = "#2C7FB8"
    marker_scale = min(
        1.0,
        math.sqrt((346.0 * 260.0) / (sensor_width * sensor_height)),
    )

    context_image = None
    for column in range(num_windows):
        start_ms, end_ms = window_bounds[column]
        current_points = point_values[column]["points"]
        current_labels = point_values[column]["labels"] >= 0.5
        current_background = current_points[~current_labels]
        current_target = current_points[current_labels]

        axes[0, column].scatter(
            current_background[:, 0],
            current_background[:, 1],
            s=2.0 * marker_scale,
            c=background_color,
            alpha=0.28,
            linewidths=0,
            rasterized=True,
        )
        if cumulative_trajectory:
            for previous in range(column):
                previous_points = point_values[previous]["points"]
                previous_labels = point_values[previous]["labels"] >= 0.5
                previous_target = previous_points[previous_labels]
                axes[0, column].scatter(
                    previous_target[:, 0],
                    previous_target[:, 1],
                    s=5.0 * marker_scale,
                    c=past_target_color,
                    alpha=0.58,
                    linewidths=0,
                    rasterized=True,
                )
        axes[0, column].scatter(
            current_target[:, 0],
            current_target[:, 1],
            s=7.0 * marker_scale,
            c=target_color,
            alpha=0.95,
            linewidths=0,
            rasterized=True,
        )

        if cumulative_trajectory:
            if column >= 2:
                axes[0, column].plot(
                    target_centroids[:column, 0],
                    target_centroids[:column, 1],
                    color=past_target_color,
                    linewidth=1.2,
                    alpha=0.75,
                    zorder=4,
                )
            if column >= 1:
                axes[0, column].plot(
                    target_centroids[column - 1 : column + 1, 0],
                    target_centroids[column - 1 : column + 1, 1],
                    color=target_color,
                    linewidth=1.8,
                    alpha=0.95,
                    zorder=5,
                )
                axes[0, column].scatter(
                    target_centroids[:column, 0],
                    target_centroids[:column, 1],
                    s=max(7.0, 12.0 * marker_scale),
                    c=past_target_color,
                    edgecolors="white",
                    linewidths=0.35,
                    zorder=6,
                )
            axes[0, column].scatter(
                target_centroids[column, 0],
                target_centroids[column, 1],
                s=max(10.0, 20.0 * marker_scale),
                c=target_color,
                edgecolors="white",
                linewidths=0.45,
                zorder=7,
            )

        context_image = axes[1, column].imshow(
            context_saliency[column],
            origin="upper",
            extent=extent,
            interpolation="nearest",
            cmap=CONTEXT_SALIENCY_COLORMAP,
            norm=saliency_norm,
        )
        axes[0, column].set_title(f"{start_ms:.0f}–{end_ms:.0f} ms")
        for row in range(2):
            axes[row, column].set_xlim(0, sensor_width)
            axes[row, column].set_ylim(sensor_height, 0)
            axes[row, column].set_aspect("equal")
            axes[row, column].set_xticks([0, sensor_width // 2, sensor_width])
            axes[row, column].set_yticks([0, sensor_height // 2, sensor_height])

    axes[0, 0].set_ylabel(
        "Cumulative GT trajectory" if cumulative_trajectory else "Raw-event GT"
    )
    axes[1, 0].set_ylabel("Relative SWC context saliency")
    for axis in axes[1, :]:
        axis.set_xlabel("x (pixel)")

    if cumulative_trajectory:
        legend_handles = [
            Line2D(
                [0],
                [0],
                marker=".",
                linestyle="none",
                color=background_color,
                label="Current-window background",
                markersize=6,
            ),
            Line2D(
                [0],
                [0],
                marker="o",
                linestyle="-",
                color=past_target_color,
                label="Past target trajectory",
                markersize=4,
            ),
            Line2D(
                [0],
                [0],
                marker="o",
                linestyle="-",
                color=target_color,
                label="New target segment",
                markersize=4,
            ),
        ]
    else:
        legend_handles = [
            Line2D(
                [0],
                [0],
                marker=".",
                linestyle="none",
                color=background_color,
                label="Background events",
                markersize=6,
            ),
            Line2D(
                [0],
                [0],
                marker=".",
                linestyle="none",
                color=target_color,
                label="Target GT events",
                markersize=8,
            ),
        ]
    fig.legend(
        handles=legend_handles,
        loc="upper center",
        bbox_to_anchor=(0.5, 1.035),
        ncol=len(legend_handles),
        frameon=False,
    )

    assert context_image is not None
    context_colorbar = fig.colorbar(
        context_image,
        ax=axes.ravel().tolist(),
        fraction=0.018,
        pad=0.015,
        extend="both",
    )
    context_colorbar.set_label(r"Relative context saliency $S_t$")

    output_stem = "swc_temporal_main"
    fig.savefig(output_dir / f"{output_stem}.png", dpi=600, bbox_inches="tight")
    fig.savefig(output_dir / f"{output_stem}.pdf", bbox_inches="tight")
    plt.close(fig)


def plot_diagnostic_figure(
    gt_ratio: np.ndarray,
    context_l2: np.ndarray,
    context_saliency: np.ndarray,
    post_prob: np.ndarray,
    delta_prob: np.ndarray,
    occupied_mask: np.ndarray,
    window_bounds: np.ndarray,
    sensor_height: int,
    sensor_width: int,
    context_limits: tuple[float, float],
    saliency_limit: float,
    delta_limit: float,
    output_path: Path,
) -> None:
    import matplotlib.pyplot as plt
    from matplotlib.colors import TwoSlopeNorm

    num_windows = gt_ratio.shape[0]
    context_vmin, context_vmax = context_limits
    saliency_norm = TwoSlopeNorm(
        vmin=-saliency_limit,
        vcenter=0.0,
        vmax=saliency_limit,
    )
    delta_norm = TwoSlopeNorm(vmin=-delta_limit, vcenter=0.0, vmax=delta_limit)
    fig, axes = plt.subplots(
        5,
        num_windows,
        figsize=(2.55 * num_windows + 1.2, 11.4),
        sharex=True,
        sharey=True,
        constrained_layout=True,
    )
    axes = np.asarray(axes).reshape(5, num_windows)
    extent = (0, sensor_width, sensor_height, 0)
    row_labels = (
        "Cell-level GT",
        "Raw context feature norm",
        "Relative context saliency",
        "Post-SWC probability",
        "SWC contribution Δp",
    )
    row_images: List[Any] = [None] * 5

    for column in range(num_windows):
        start_ms, end_ms = window_bounds[column]
        post_display = post_prob[column].copy()
        post_display[~occupied_mask[column]] = np.nan
        row_values = (
            (gt_ratio[column], "Reds", 0.0, 1.0, None),
            (
                context_l2[column],
                RAW_CONTEXT_COLORMAP,
                context_vmin,
                context_vmax,
                None,
            ),
            (
                context_saliency[column],
                CONTEXT_SALIENCY_COLORMAP,
                None,
                None,
                saliency_norm,
            ),
            (post_display, "viridis", 0.0, 1.0, None),
            (delta_prob[column], "RdBu_r", None, None, delta_norm),
        )
        for row, (values, cmap, vmin, vmax, norm) in enumerate(row_values):
            kwargs: Dict[str, Any] = {
                "origin": "upper",
                "extent": extent,
                "interpolation": "nearest",
                "cmap": cmap,
            }
            if norm is not None:
                kwargs["norm"] = norm
            else:
                kwargs["vmin"] = vmin
                kwargs["vmax"] = vmax
            row_images[row] = axes[row, column].imshow(values, **kwargs)
            axes[row, column].set_xlim(0, sensor_width)
            axes[row, column].set_ylim(sensor_height, 0)
            axes[row, column].set_aspect("equal")
        axes[0, column].set_title(f"{start_ms:.0f}–{end_ms:.0f} ms")

    for row, label in enumerate(row_labels):
        axes[row, 0].set_ylabel(label)
        colorbar_kwargs: Dict[str, Any] = {}
        if row in (1, 2, 4):
            colorbar_kwargs["extend"] = "both"
        fig.colorbar(
            row_images[row],
            ax=axes[row, :],
            fraction=0.018,
            pad=0.015,
            **colorbar_kwargs,
        )
    for axis in axes[-1, :]:
        axis.set_xlabel("x (pixel)")

    fig.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close(fig)


def write_metrics_csv(path: Path, rows: Sequence[Mapping[str, Any]]) -> None:
    if not rows:
        raise ValueError("No window metrics to write")
    fieldnames = list(rows[0].keys())
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def concatenate_point_values(
    per_window: Sequence[Mapping[str, np.ndarray]],
) -> Dict[str, np.ndarray]:
    offsets = [0]
    for values in per_window:
        offsets.append(offsets[-1] + int(values["labels"].shape[0]))
    output: Dict[str, np.ndarray] = {
        "point_offsets": np.asarray(offsets, dtype=np.int64)
    }
    for key in ("points", "labels", "cell_idx", "pre_prob", "post_prob", "delta_prob"):
        output[f"point_{key}"] = np.concatenate(
            [values[key] for values in per_window],
            axis=0,
        )
    return output


def verify_arrays(arrays: Mapping[str, np.ndarray], expected_shape: tuple[int, ...]) -> None:
    required = (
        "gt_ratio",
        "delta_prob",
        "context_l2",
        "context_standardized_energy",
        "context_smoothed_energy",
        "context_local_median",
        "context_saliency",
        "post_prob",
        "occupied_mask",
        "event_count",
        "target_count",
    )
    for key in required:
        value = arrays[key]
        if value.shape != expected_shape:
            raise AssertionError(f"{key} has shape {value.shape}, expected {expected_shape}")
        if not np.isfinite(value).all():
            raise AssertionError(f"{key} contains non-finite values")


def main() -> int:
    args = parse_args()
    config_path = resolve_path(args.config)
    checkpoint_path = resolve_path(args.checkpoint)
    sample_path = resolve_path(args.sample)
    output_dir = resolve_path(args.output_dir)

    for path, label in (
        (config_path, "config"),
        (checkpoint_path, "checkpoint"),
        (sample_path, "sample"),
    ):
        if not path.is_file():
            raise FileNotFoundError(f"{label} file not found: {path}")

    validate_args(args)
    prepare_output_dir(output_dir, args.overwrite)
    setup_runtime(seed=37)
    configure_matplotlib()

    cfg, _ = read_config(config_path)
    from model.Grid_Mamba.grid_mamba_net import GridMambaNet

    device = torch.device(args.device)
    model = GridMambaNet(cfg).eval().to(device)
    checkpoint = torch.load(checkpoint_path, map_location=device)
    model.load_state_dict(checkpoint, strict=True)
    validate_model_config(model, cfg)

    points_np, labels_np = load_sample(sample_path)
    points = torch.from_numpy(points_np).to(device=device, dtype=torch.float32)
    labels = torch.from_numpy(labels_np).to(device=device, dtype=torch.float32)
    window_layout = make_window_layout(points, labels, model.window_size)
    num_model_windows = int(window_layout["counts"].numel())
    stop_window = args.start_window + args.num_windows
    if stop_window > num_model_windows:
        raise ValueError(
            f"Requested windows [{args.start_window}, {stop_window}) but sample "
            f"contains only {num_model_windows} model windows"
        )

    print(f"config: {relative_or_absolute(config_path)}")
    print(f"checkpoint: {relative_or_absolute(checkpoint_path)}")
    print(f"sample: {relative_or_absolute(sample_path)}")
    print(
        f"capturing windows {args.start_window}–{stop_window - 1} "
        f"from {num_model_windows} total windows"
    )

    with torch.inference_mode():
        reference_logits, _ = model(points)
        traced_logits, captures = capture_swc_windows(
            model,
            points,
            start_window=args.start_window,
            num_windows=args.num_windows,
        )

    if reference_logits is None:
        raise RuntimeError("Reference model run returned no logits")
    torch.testing.assert_close(
        traced_logits,
        reference_logits,
        rtol=1e-5,
        atol=1e-6,
    )
    max_logit_difference = float(
        (traced_logits.float() - reference_logits.float()).abs().max().item()
    )

    token_h = model.spatial_window_context.spatial_token_h
    token_w = model.spatial_window_context.spatial_token_w
    sensor_height = int(model.sensor_height)
    sensor_width = int(model.sensor_width)
    dataset_hint = " ".join(
        (
            str(getattr(cfg, "dataset_name", "")),
            str(getattr(cfg, "root", "")),
            str(sample_path),
        )
    ).lower()
    normalized_dataset_hint = dataset_hint.replace("_", "-")
    if "ev-uav" in normalized_dataset_hint or "evuav" in normalized_dataset_hint:
        dataset_label = "EVUAV"
    elif "ev-flying" in normalized_dataset_hint:
        dataset_label = "EV-Flying"
    else:
        dataset_label = str(getattr(cfg, "dataset_name", "unknown")) or "unknown"
    offsets = window_layout["offsets"]
    labels_sorted = window_layout["labels"]
    points_sorted = window_layout["points"]
    sample_t0 = float(points_sorted[0, 2].item())

    map_rows: List[Mapping[str, np.ndarray]] = []
    metric_rows: List[Dict[str, Any]] = []
    point_rows: List[Mapping[str, np.ndarray]] = []
    raw_token_features: List[np.ndarray] = []
    effective_token_features: List[np.ndarray] = []
    context_features: List[np.ndarray] = []
    centroids: List[np.ndarray] = []
    window_bounds: List[tuple[float, float]] = []
    quality_warnings: List[str] = []

    for capture in captures:
        window_index = int(capture["window_index"].item())
        start = int(offsets[window_index].item())
        end = int(offsets[window_index + 1].item())
        expected_points = points_sorted[start:end].detach().float().cpu()
        torch.testing.assert_close(capture["points"], expected_points)

        maps, metrics, point_values = aggregate_cell_values(
            capture,
            labels_sorted[start:end],
            token_h=token_h,
            token_w=token_w,
            threshold=args.threshold,
        )
        start_ms = sample_t0 + window_index * model.window_size
        end_ms = start_ms + model.window_size
        metrics = {
            "window_index": window_index,
            "start_ms": start_ms,
            "end_ms": end_ms,
            **metrics,
        }
        if metrics["num_target_events"] <= 0:
            raise AssertionError(f"Window {window_index} contains no target events")
        if (
            metrics["mean_delta_target_cells"]
            <= metrics["mean_delta_background_cells"]
        ):
            quality_warnings.append(
                f"Window {window_index} does not have stronger mean SWC contribution "
                "on target cells than background cells"
            )
        if (
            metrics["mean_context_target_cells"]
            <= metrics["mean_context_background_cells"]
        ):
            quality_warnings.append(
                f"Window {window_index} does not have stronger mean context norm "
                "on target cells than background cells"
            )

        map_rows.append(maps)
        metric_rows.append(metrics)
        point_rows.append(point_values)
        raw_token_features.append(capture["raw_token_map"].numpy())
        effective_token_features.append(capture["effective_token_map"].numpy())
        context_features.append(capture["context_map"].numpy())
        centroids.append(
            np.asarray([metrics["centroid_x"], metrics["centroid_y"]], dtype=np.float32)
        )
        window_bounds.append((start_ms, end_ms))

    stacked_maps: Dict[str, np.ndarray] = {
        key: np.stack([maps[key] for maps in map_rows], axis=0)
        for key in map_rows[0]
    }
    context_features_np = np.stack(context_features, axis=0).astype(np.float32)
    derived_context = compute_gt_free_context_saliency(context_features_np)
    for key in (
        "context_standardized_energy",
        "context_smoothed_energy",
        "context_local_median",
        "context_saliency",
    ):
        stacked_maps[key] = derived_context[key]
    expected_shape = (args.num_windows, token_h, token_w)
    verify_arrays(stacked_maps, expected_shape)

    centroids_np = np.stack(centroids, axis=0)
    steps = np.linalg.norm(np.diff(centroids_np, axis=0), axis=1)
    endpoint_displacement = float(np.linalg.norm(centroids_np[-1] - centroids_np[0]))
    path_length = float(steps.sum())
    cell_displacement = endpoint_displacement / float(
        model.spatial_window_context.spatial_context_stride
    )
    for index, metrics in enumerate(metric_rows):
        metrics["step_displacement_px"] = 0.0 if index == 0 else float(steps[index - 1])
        metrics["cumulative_path_px"] = (
            0.0 if index == 0 else float(steps[:index].sum())
        )
        target_cells = stacked_maps["target_count"][index] > 0
        background_cells = stacked_maps["occupied_mask"][index] & ~target_cells
        saliency = stacked_maps["context_saliency"][index]
        metrics["mean_context_saliency_target_cells"] = float(
            saliency[target_cells].mean()
        )
        metrics["mean_context_saliency_background_cells"] = float(
            saliency[background_cells].mean()
        )
        metrics["auc_context_saliency"] = auc_binary(
            target_cells[stacked_maps["occupied_mask"][index]].astype(np.int64),
            saliency[stacked_maps["occupied_mask"][index]],
        )
        peak_y, peak_x = np.unravel_index(
            int(np.argmax(saliency)),
            saliency.shape,
        )
        stride = float(model.spatial_window_context.spatial_context_stride)
        peak_xy = np.asarray(
            [(peak_x + 0.5) * stride, (peak_y + 0.5) * stride],
            dtype=np.float32,
        )
        metrics["context_saliency_peak_x"] = float(peak_xy[0])
        metrics["context_saliency_peak_y"] = float(peak_xy[1])
        metrics["context_saliency_peak_to_gt_centroid_px"] = float(
            np.linalg.norm(peak_xy - centroids_np[index])
        )

    occupied_values = np.concatenate(
        [
            stacked_maps["delta_prob"][index][stacked_maps["occupied_mask"][index]]
            for index in range(args.num_windows)
        ]
    )
    delta_limit = robust_symmetric_limit(occupied_values, quantile=0.99)
    context_limits = shared_percentile_limits(
        stacked_maps["context_l2"],
        low=RAW_CONTEXT_COLOR_LOW_QUANTILE,
        high=RAW_CONTEXT_COLOR_HIGH_QUANTILE,
    )
    saliency_limit = robust_symmetric_limit(
        stacked_maps["context_saliency"],
        quantile=CONTEXT_SALIENCY_COLOR_QUANTILE,
    )
    window_bounds_np = np.asarray(window_bounds, dtype=np.float32)

    plot_main_figure(
        point_rows,
        centroids_np,
        stacked_maps["context_saliency"],
        window_bounds_np,
        sensor_height=sensor_height,
        sensor_width=sensor_width,
        saliency_limit=saliency_limit,
        output_dir=output_dir,
        cumulative_trajectory=True,
    )
    plot_diagnostic_figure(
        stacked_maps["gt_ratio"],
        stacked_maps["context_l2"],
        stacked_maps["context_saliency"],
        stacked_maps["post_prob"],
        stacked_maps["delta_prob"],
        stacked_maps["occupied_mask"],
        window_bounds_np,
        sensor_height=sensor_height,
        sensor_width=sensor_width,
        context_limits=context_limits,
        saliency_limit=saliency_limit,
        delta_limit=delta_limit,
        output_path=output_dir / "swc_temporal_diagnostic.png",
    )

    point_arrays = concatenate_point_values(point_rows)
    np.savez_compressed(
        output_dir / "swc_temporal_maps.npz",
        **stacked_maps,
        window_indices=np.asarray(
            [row["window_index"] for row in metric_rows], dtype=np.int64
        ),
        window_bounds_ms=window_bounds_np,
        target_centroids_xy=centroids_np,
        target_step_displacements_px=steps.astype(np.float32),
        raw_token_features=np.stack(raw_token_features, axis=0).astype(np.float32),
        effective_token_features=np.stack(effective_token_features, axis=0).astype(
            np.float32
        ),
        context_features=context_features_np,
        context_channel_center=derived_context["context_channel_center"],
        context_channel_scale=derived_context["context_channel_scale"],
        context_channel_scale_source=derived_context[
            "context_channel_scale_source"
        ],
        **point_arrays,
    )
    write_metrics_csv(output_dir / "window_metrics.csv", metric_rows)

    scale_source = derived_context["context_channel_scale_source"]
    scale_source_counts = {
        "mad": int(np.sum(scale_source == 0)),
        "iqr_fallback": int(np.sum(scale_source == 1)),
        "standard_deviation_fallback": int(np.sum(scale_source == 2)),
        "inactive_constant": int(np.sum(scale_source == 3)),
    }
    summary = {
        "schema_version": 5,
        "dataset": dataset_label,
        "figure": "section_1.3.2_swc_temporal_context",
        "config": relative_or_absolute(config_path),
        "checkpoint": relative_or_absolute(checkpoint_path),
        "checkpoint_sha256": sha256_file(checkpoint_path),
        "sample": relative_or_absolute(sample_path),
        "device": str(device),
        "threshold": float(args.threshold),
        "start_window": int(args.start_window),
        "num_windows": int(args.num_windows),
        "window_indices": [int(row["window_index"]) for row in metric_rows],
        "window_bounds_ms": window_bounds_np.tolist(),
        "window_size_ms": float(model.window_size),
        "sensor_size_hw": [sensor_height, sensor_width],
        "spatial_context_stride": float(
            model.spatial_window_context.spatial_context_stride
        ),
        "spatial_token_shape_hw": [token_h, token_w],
        "feature_channels": int(context_features[0].shape[-1]),
        "main_gt_definition": "current-window background; prior target events and centroids blue; newly appended target events and centroid segment red",
        "heatmap_definition": (
            "GT-free relative SWC context saliency: per-channel median/MAD "
            "standardization over all selected windows and cells; RMS channel "
            "energy; 3x3 binomial smoothing; minus 7x7 local spatial median"
        ),
        "heatmap_equation": (
            "Z=(C-median(C))/(1.4826*MAD(C)); E=sqrt(mean_channels(Z^2)); "
            "S=binomial3x3(E)-median7x7(binomial3x3(E))"
        ),
        "heatmap_cell_coverage": (
            f"all {token_h}x{token_w} cells; no occupied-cell mask"
        ),
        "heatmap_gt_overlay": False,
        "heatmap_gt_used_for_computation": False,
        "heatmap_inputs": ["context_features"],
        "heatmap_excluded_inputs": [
            "ground_truth",
            "occupied_mask",
            "point_probabilities",
            "target_centroids",
        ],
        "heatmap_colormap": CONTEXT_SALIENCY_COLORMAP,
        "heatmap_scale": "linear_diverging_centered_at_zero",
        "heatmap_color_limits": [-saliency_limit, saliency_limit],
        "heatmap_color_limit_rule": (
            "shared symmetric range using the 99.5th percentile of absolute "
            "context_saliency across all cells and selected windows; display "
            "clipping only"
        ),
        "context_channel_center_rule": (
            "per-channel median across selected windows and all spatial cells"
        ),
        "context_channel_scale_rule": (
            "1.4826 times per-channel MAD; IQR then standard deviation fallback "
            "for zero-MAD channels; constant channels contribute zero"
        ),
        "context_channel_scale_epsilon": ROBUST_SCALE_EPSILON,
        "context_channel_scale_source_counts": scale_source_counts,
        "context_energy_definition": (
            f"root mean square of robust-standardized values across "
            f"{context_features[0].shape[-1]} channels"
        ),
        "context_spatial_smoothing": "reflection-padded 3x3 binomial filter",
        "context_local_background": (
            "reflection-padded 7x7 median of smoothed standardized energy"
        ),
        "gt_usage_note": (
            "GT is used only for the first-row reference and after-the-fact "
            "evaluation metrics; it is not used to construct or scale the heatmap"
        ),
        "diagnostic_delta_definition": "mean(sigmoid(logit_after_swc) - sigmoid(logit_before_swc)) per occupied cell",
        "diagnostic_delta_empty_cell_value": 0.0,
        "delta_color_limit": float(delta_limit),
        "delta_color_limit_rule": "symmetric 99th percentile of absolute occupied-cell delta across selected windows",
        "raw_context_diagnostic_definition": (
            f"L2 norm of the {context_features[0].shape[-1]}-channel raw "
            "context_map per cell"
        ),
        "raw_context_diagnostic_colormap": RAW_CONTEXT_COLORMAP,
        "raw_context_diagnostic_limits": list(context_limits),
        "raw_context_diagnostic_limit_rule": (
            "shared 50th and 99.5th percentiles of context_l2 across all cells "
            "and selected windows; display clipping only"
        ),
        "context_saliency_color_limit": float(saliency_limit),
        "target_centroids_xy": centroids_np.tolist(),
        "endpoint_displacement_px": endpoint_displacement,
        "path_length_px": path_length,
        "endpoint_displacement_cells": cell_displacement,
        "trace_reference_max_abs_logit_difference": max_logit_difference,
        "trace_reference_allclose": True,
        "quality_warnings": quality_warnings,
        "model_switches": {
            "use_ts_embedding": bool(model.use_ts_embedding),
            "use_sparse_conv_encoder": bool(model.use_sparse_conv_encoder),
            "use_knn_spatial_encoder": bool(model.use_knn_spatial_encoder),
            "use_grid_pos_encoding": bool(model.use_grid_pos_encoding),
            "use_spatial_window_context": bool(model.use_spatial_window_context),
            "use_temporal_cell_diffusion": bool(
                model.spatial_window_context.use_temporal_cell_diffusion
            ),
        },
        "window_metrics": metric_rows,
        "outputs": {name: name for name in OUTPUT_FILES if name != "summary.json"},
    }
    with (output_dir / "summary.json").open("w", encoding="utf-8") as handle:
        json.dump(summary, handle, ensure_ascii=False, indent=2, default=json_value)
        handle.write("\n")

    print(f"trace/reference max |Δlogit|: {max_logit_difference:.3e}")
    print(
        f"target endpoint displacement: {endpoint_displacement:.1f} px "
        f"({cell_displacement:.1f} SWC cells), path length: {path_length:.1f} px"
    )
    for row in metric_rows:
        print(
            f"window {row['window_index']:02d} {row['start_ms']:.0f}–{row['end_ms']:.0f} ms: "
            f"events={row['num_events']}, target={row['num_target_events']}, "
            f"IoU={row['iou']:.4f}, AUC(Δp)={row['auc_delta_prob']:.4f}, "
            f"AUC(context L2)={row['auc_context_l2']:.4f}, "
            f"AUC(context saliency)={row['auc_context_saliency']:.4f}"
        )
    for warning in quality_warnings:
        print(f"warning: {warning}")
    print(f"wrote outputs to: {output_dir}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise
